# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homep.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1056, 801)
        Form.setStyleSheet("background-color:#a9cad9")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 184, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("probirka.png"))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color:white;")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(470, 760, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #35525e;")
        self.label_3.setObjectName("label_3")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(420, 100, 591, 581))
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stackedWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.stackedWidget.setStyleSheet("QStackedWidget{\n"
"background-color:#a9cad9;\n"
"}")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.page_0.setObjectName("page_0")
        self.stackedWidget.addWidget(self.page_0)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.lineEdit_poss = QtWidgets.QLineEdit(self.page)
        self.lineEdit_poss.setGeometry(QtCore.QRect(20, 20, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_poss.setFont(font)
        self.lineEdit_poss.setStyleSheet("background-color: white;")
        self.lineEdit_poss.setObjectName("lineEdit_poss")
        self.poisk_pos = QtWidgets.QPushButton(self.page)
        self.poisk_pos.setGeometry(QtCore.QRect(190, 20, 75, 23))
        self.poisk_pos.setStyleSheet("QPushButton{\n"
"    -webkit-transition-duration: 0.4s; \n"
"    transition-duration: 0.4s;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"    border: 1px solid #35525e;\n"
"    color: #35525e;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #35525e;\n"
"    color: white;\n"
"}")
        self.poisk_pos.setObjectName("poisk_pos")
        self.add_pos = QtWidgets.QPushButton(self.page)
        self.add_pos.setGeometry(QtCore.QRect(270, 20, 131, 23))
        self.add_pos.setStyleSheet("QPushButton{\n"
"    -webkit-transition-duration: 0.4s; \n"
"    transition-duration: 0.4s;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"    border: 1px solid #35525e;\n"
"    color: #35525e;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #35525e;\n"
"    color: white;\n"
"}")
        self.add_pos.setObjectName("add_pos")
        self.del_pos = QtWidgets.QPushButton(self.page)
        self.del_pos.setGeometry(QtCore.QRect(460, 20, 75, 23))
        self.del_pos.setStyleSheet("QPushButton{\n"
"    -webkit-transition-duration: 0.4s; \n"
"    transition-duration: 0.4s;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"    border: 1px solid #35525e;\n"
"    color: #35525e;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #35525e;\n"
"    color: white;\n"
"}")
        self.del_pos.setObjectName("del_pos")
        self.listWidget = QtWidgets.QListWidget(self.page)
        self.listWidget.setGeometry(QtCore.QRect(10, 60, 571, 461))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("background-color: white;\n"
"QListWidget.items{\n"
"background-color: blue;\n"
"}")
        self.listWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget.setLineWidth(1)
        self.listWidget.setObjectName("listWidget")
        self.obnov_analiz = QtWidgets.QPushButton(self.page)
        self.obnov_analiz.setGeometry(QtCore.QRect(260, 540, 75, 23))
        self.obnov_analiz.setStyleSheet("QPushButton{\n"
"    -webkit-transition-duration: 0.4s; \n"
"    transition-duration: 0.4s;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"    border: 1px solid #35525e;\n"
"    color: #35525e;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #35525e;\n"
"    color: white;\n"
"}")
        self.obnov_analiz.setObjectName("obnov_analiz")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.lineEdit_prep = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_prep.setGeometry(QtCore.QRect(20, 20, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_prep.setFont(font)
        self.lineEdit_prep.setStyleSheet("background-color: white;")
        self.lineEdit_prep.setText("")
        self.lineEdit_prep.setObjectName("lineEdit_prep")
        self.run_prep = QtWidgets.QPushButton(self.page_2)
        self.run_prep.setGeometry(QtCore.QRect(220, 20, 75, 23))
        self.run_prep.setStyleSheet("QPushButton{\n"
"    -webkit-transition-duration: 0.4s; \n"
"    transition-duration: 0.4s;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"    border: 1px solid #35525e;\n"
"    color: #35525e;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #35525e;\n"
"    color: white;\n"
"}")
        self.run_prep.setObjectName("run_prep")
        self.add_prep = QtWidgets.QPushButton(self.page_2)
        self.add_prep.setGeometry(QtCore.QRect(300, 20, 131, 23))
        self.add_prep.setStyleSheet("QPushButton{\n"
"    -webkit-transition-duration: 0.4s; \n"
"    transition-duration: 0.4s;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"    border: 1px solid #35525e;\n"
"    color: #35525e;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #35525e;\n"
"    color: white;\n"
"}")
        self.add_prep.setObjectName("add_prep")
        self.run_prep_2 = QtWidgets.QPushButton(self.page_2)
        self.run_prep_2.setGeometry(QtCore.QRect(470, 20, 75, 23))
        self.run_prep_2.setStyleSheet("QPushButton{\n"
"    -webkit-transition-duration: 0.4s; \n"
"    transition-duration: 0.4s;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"    border: 1px solid #35525e;\n"
"    color: #35525e;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #35525e;\n"
"    color: white;\n"
"}")
        self.run_prep_2.setObjectName("run_prep_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.page_2)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 60, 571, 461))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(12)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setStyleSheet("background-color: white;")
        self.listWidget_2.setObjectName("listWidget_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.lineEdit_analiz = QtWidgets.QLineEdit(self.page_1)
        self.lineEdit_analiz.setGeometry(QtCore.QRect(20, 20, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_analiz.setFont(font)
        self.lineEdit_analiz.setStyleSheet("background-color: white;")
        self.lineEdit_analiz.setObjectName("lineEdit_analiz")
        self.run_analiz = QtWidgets.QPushButton(self.page_1)
        self.run_analiz.setGeometry(QtCore.QRect(220, 20, 75, 23))
        self.run_analiz.setStyleSheet("QPushButton{\n"
"    -webkit-transition-duration: 0.4s; \n"
"    transition-duration: 0.4s;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"    border: 1px solid #35525e;\n"
"    color: #35525e;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #35525e;\n"
"    color: white;\n"
"}")
        self.run_analiz.setObjectName("run_analiz")
        self.add_analiz = QtWidgets.QPushButton(self.page_1)
        self.add_analiz.setGeometry(QtCore.QRect(300, 20, 131, 23))
        self.add_analiz.setStyleSheet("QPushButton{\n"
"    -webkit-transition-duration: 0.4s; \n"
"    transition-duration: 0.4s;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"    border: 1px solid #35525e;\n"
"    color: #35525e;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #35525e;\n"
"    color: white;\n"
"}")
        self.add_analiz.setObjectName("add_analiz")
        self.run_analiz_2 = QtWidgets.QPushButton(self.page_1)
        self.run_analiz_2.setGeometry(QtCore.QRect(470, 20, 75, 23))
        self.run_analiz_2.setStyleSheet("QPushButton{\n"
"    -webkit-transition-duration: 0.4s; \n"
"    transition-duration: 0.4s;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"    border: 1px solid #35525e;\n"
"    color: #35525e;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #35525e;\n"
"    color: white;\n"
"}")
        self.run_analiz_2.setObjectName("run_analiz_2")
        self.listWidget_3 = QtWidgets.QListWidget(self.page_1)
        self.listWidget_3.setGeometry(QtCore.QRect(10, 60, 571, 461))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(12)
        self.listWidget_3.setFont(font)
        self.listWidget_3.setStyleSheet("background-color: white;")
        self.listWidget_3.setObjectName("listWidget_3")
        self.stackedWidget.addWidget(self.page_1)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 160, 271, 251))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.poseshenia = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.poseshenia.sizePolicy().hasHeightForWidth())
        self.poseshenia.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.poseshenia.setFont(font)
        self.poseshenia.setStyleSheet("QPushButton{\n"
"    -webkit-transition-duration: 0.4s; \n"
"    transition-duration: 0.4s;\n"
"    border-radius: 10px;\n"
"    background-color:#a9cad9;\n"
"    border: 2px solid #35525e;\n"
"    color:#35525e;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #35525e;\n"
"    color: white;\n"
"}")
        self.poseshenia.setObjectName("poseshenia")
        self.verticalLayout.addWidget(self.poseshenia)
        self.analizi = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analizi.sizePolicy().hasHeightForWidth())
        self.analizi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.analizi.setFont(font)
        self.analizi.setStyleSheet("QPushButton{\n"
"    -webkit-transition-duration: 0.4s; \n"
"    transition-duration: 0.4s;\n"
"    border-radius: 10px;\n"
"    background-color:#a9cad9;\n"
"    border: 2px solid #35525e;\n"
"    color: #35525e;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #35525e;\n"
"    color: white;\n"
"}")
        self.analizi.setObjectName("analizi")
        self.verticalLayout.addWidget(self.analizi)
        self.preparati = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preparati.sizePolicy().hasHeightForWidth())
        self.preparati.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.preparati.setFont(font)
        self.preparati.setStyleSheet("QPushButton{\n"
"    -webkit-transition-duration: 0.4s; \n"
"    transition-duration: 0.4s;\n"
"    border-radius: 10px;\n"
"    background-color:#a9cad9;\n"
"    border: 2px solid #35525e;\n"
"    color: #35525e;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #35525e;\n"
"    color: white;\n"
"}")
        self.preparati.setObjectName("preparati")
        self.verticalLayout.addWidget(self.preparati)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Immuno"))
        self.label_3.setText(_translate("Form", "@ssooybean"))
        self.lineEdit_poss.setPlaceholderText(_translate("Form", "Cпециализация врача..."))
        self.poisk_pos.setText(_translate("Form", "Поиск"))
        self.add_pos.setText(_translate("Form", "Добавить записть"))
        self.del_pos.setText(_translate("Form", "Удалить"))
        self.obnov_analiz.setText(_translate("Form", "Обновить"))
        self.lineEdit_prep.setPlaceholderText(_translate("Form", "Название препарата..."))
        self.run_prep.setText(_translate("Form", "Поиск"))
        self.add_prep.setText(_translate("Form", "Добавить записть"))
        self.run_prep_2.setText(_translate("Form", "Удалить"))
        self.lineEdit_analiz.setPlaceholderText(_translate("Form", "Название файла..."))
        self.run_analiz.setText(_translate("Form", "Поиск"))
        self.add_analiz.setText(_translate("Form", "Добавить записть"))
        self.run_analiz_2.setText(_translate("Form", "Удалить"))
        self.layoutWidget1.setStyleSheet(_translate("Form", "QPushButton{\n"
"    color: white;\n"
"    background-color: #35525e;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #436878;\n"
"}\n"
"border-radius: 8px;"))
        self.poseshenia.setText(_translate("Form", "Посещения"))
        self.analizi.setText(_translate("Form", "Анализы"))
        self.preparati.setText(_translate("Form", "Принимаемые препараты"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
